### ISSUE TITLE
Windows stack support

### ISSUE THREAD

**Issue by simon2b** [bitrise-io/bitrise.io#105]
Hi,

Im interested in the possibility of running a windows stack for building platforms such as HoloLens, Vive, Windows Phone etc.

Is this something that is going to be feasible anytime soon?

Thanks

**Comment by viktorbenei** [comment]
We definitely have plans, but not in the near future. Feel free to vote on this feature request: https://bitrise.uservoice.com/forums/235233-general/suggestions/13347087-there-shall-be-xamarin-for-windows

**Comment by viktorbenei** [comment]
This issue was moved to https://discuss.bitrise.io/t/windows-stack-support/142
