### ISSUE TITLE
Missing Github repositories

### ISSUE THREAD

**Issue by soundbites** [bitrise-io/bitrise.io#11]
Hi,
when trying to select my repository with Github, I'm missing a lot of repositories from the list. (I'm part of 3 organisations which have a lot of repo's)

Is there some limit to the number of Git repo's it will list?

The only way of connecting to some of my github repos is by configuring it manually.

**Comment by viktorbenei** [comment]
Hi, you should enable the organizations access on GitHub for Bitrise. It was a recent change on GitHub. You can check the organization access at https://github.com/settings/applications - select Bitrise and in the `Organization access` section you can see which organizations can be accessed by Bitrise.

**Comment by soundbites** [comment]
I checked, and Bitrise is added to the application access.

<img width="744" alt="screen shot 2015-09-08 at 10 58 50" src="https://cloud.githubusercontent.com/assets/596438/9730723/b1a8adde-5618-11e5-8f83-07d7ca1d6c4c.png">

**Comment by viktorbenei** [comment]
Click on it and you'll see whether it has access to the organizations in the `Organization access` section.

**Comment by soundbites** [comment]
You are absolutely right, fixed thx!

**Comment by viktorbenei** [comment]
No problem at all, to be honest this change in GitHub is quite a PITA..
