### ISSUE TITLE
Problem with Jest appeared

### ISSUE THREAD

**Issue by sam-nicolai** [bitrise-io/bitrise.io#110]
Hello,

I'm using Jest to run the tests for my react native app. I ran a test on December 23rd and everything passed. If I now run the same commit today on my mac (OSX 10.12.2) or my windows 10 machine, everything passes fine, but if I run the same one on bitrise, the tests don't pass with a snapshot error message:
```
 FAIL  tests/unit/src/ui/SingupLogin.test.js
  ● The page › should render correctly

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -1,9 +1,9 @@
     <ScrollView
       contentInset={
         Object {
    -      "bottom": 49,
    +      "bottom": 0,
         }
       }
       enableAutoAutomaticScroll={true}
       extraHeight={75}
       extraScrollHeight={0}
      
      at Object.<anonymous> (tests/unit/src/ui/SingupLogin.test.js:28:14)
``` 

I tried the OSX stack, ubuntu 16 and get the same problem on all of them. On ubunut 14, npm install crashes (I don't know if this is new, since I was always using 16)... I checked the linux-docker-android.log, but no red flag came up, all the versions seem to be essentially what I have on my machines. I see there was only one update for the VMs since december 23rd.

**Comment by sam-nicolai** [comment]
I upgraded to the latest versions of jest, react and react-native and the problem went away. This is not a problem with BitRise! 
Sorry

**Comment by viktorbenei** [comment]
Thanks for sharing the solution! :)
