### ISSUE TITLE
Fastlane gym action fails selecting the right scheme

### ISSUE THREAD

**Issue by soundbites** [bitrise-io/bitrise.io#12]
Hi,
locally I'm using fastlane with cocoapods to build and deliver my app.

When the gym action is run, it will fail on Bitrise when selecting the appropriate scheme "Recruitment";
$ xcrun xcodebuild -list -workspace './Recruitment.xcworkspace'

Locally it just works fine.

**Comment by viktorbenei** [comment]
`xcodebuild` requires the scheme to be specified directly, with `-scheme YourScheme`

**Comment by viktorbenei** [comment]
Maybe the scheme is not specified in your Fastfile / fastlane config, only on your local machine?

**Comment by birmacher** [comment]
Hey @soundbites! Can you please check if you have shared your scheme?
If that's shared can you please share your Fastfile so I can dig in a bit to find the issue.

**Comment by soundbites** [comment]
Yes it was shared, but I've found the problem. I was using the wrong Scheme name. But weird that it was working locally.

sorry for the inconvenience! and thanks for the time to answer my question!

**Comment by viktorbenei** [comment]
No problem at all, we always learn something from every solved issue :)
