### ISSUE TITLE
Error in deploy

### ISSUE THREAD

**Issue by Den-Ree** [bitrise-io/bitrise.io#122]
Hi, guys! 
Could you, please, help me with deploy?

I have gotten the error:
Deploy source path does not exist at the provided path: /Users/vagrant/deploy/<ProjectName>/builds
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | deploy-to-bitrise-io@1.2.7 (exit code: 1)                     | 8.20 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...://github.com/bitrise-io/steps-deploy-to-bitrise-io/issues |
| Source: https://github.com/bitrise-io/steps-deploy-to-bitrise-io     

and in my script "Deploy to Bitrise"
$BITRISE_DEPLOY_DIR/<Project name>/builds/

I have this task to do:
- Add ‘/builds/’ to the deploy directory. Pre x ‘/builds/‘ with the sub-directory if Xcode project is located in one. 

When I remove  <Project name> from path, I have the same error.

**Comment by viktorbenei** [comment]
What do you try to deploy? An iOS app?

Asking, because you should not have to change any parameter of this step (deploy to bitrise.io), the default config should deploy the files from the `$BITRISE_DEPLOY_DIR` directory, and our own steps move the generated app files there.

**Comment by Den-Ree** [comment]
@viktorbenei  Yes, iOS app.
So should I leave only $BITRISE_DEPLOY_DIR?

**Comment by viktorbenei** [comment]
> So should I leave only $BITRISE_DEPLOY_DIR?

Correct, if you use e.g. the Xcode Archive step, that will move the generated IPA into the $BITRISE_DEPLOY_DIR directory automatically.

**Comment by Den-Ree** [comment]
It passed, thanks for quick help) 
Have  a nice day.

**Comment by viktorbenei** [comment]
Any time 😉
