### ISSUE TITLE
Cannot find tag when cloning repository

### ISSUE THREAD

**Issue by maoueh** [bitrise-io/bitrise.io#127]
Sometimes when I push tag and start a build manually, the build failed at the clone step saying tag is not present.

It's really clear why it's not working correctly as cloning to `/tmp` dir on my work machine list all the tags correctly.

At 10:29 (EST), I pushed a tag `v1.0.1.beta.4` to the repository:

```
> 10:29:50 directlink-android git:(master)
$ git push origin v1.0.1.beta.4
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 476 bytes | 0 bytes/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:samsao/directlink-android.git
 * [new tag]           v1.0.1.beta.4 -> v1.0.1.beta.4
```

Then started a build with a specific tag (https://www.bitrise.io/build/6e06bb5615452093). This one failed saying the tag does not exist:

```
...
error: pathspec 'v1.0.1.beta.4' did not match any file(s) known to git.
Error: Could not do checkout v1.0.1.beta.4
Clone Is Success?: false
Cloned commit hash: 
 (i) Removing private key file: /root/.ssh/bitrise
rm: invalid option -- 'P'
Try 'rm --help' for more information.
```

Indeed, in the log tag listing, I do not see it in the list. I rebuild this build and failed with the same error message (https://www.bitrise.io/build/39223fcbbfbc27db). 

Then, I clone the repository on my `/tmp` folder to check if it would work from my side:

```
> 10:43:17 directlink-android git:(master)
$ cd /tmp

> 10:43:26 /tmp
$ git clone git@github.com:samsao/directlink-android.git
Cloning into 'directlink-android'...
remote: Counting objects: 28918, done.
remote: Compressing objects: 100% (383/383), done.
remote: Total 28918 (delta 663), reused 467 (delta 467), pack-reused 27951
Receiving objects: 100% (28918/28918), 12.08 MiB | 2.42 MiB/s, done.
Resolving deltas: 100% (16149/16149), done.

> 10:43:38 /tmp
$ cd directlink-android

> 10:43:44 /tmp/directlink-android git:(develop)
$ git tag -l
EditConfigurationPreviousInstallFlow
v0.5.0
v0.6.0
v0.7.0
v0.8.0
v1.0.0
v1.0.0.beta.16
v1.0.0.beta.17
v1.0.0.beta.18
v1.0.1.beta.1
v1.0.1.beta.2
v1.0.1.beta.3
v1.0.1.beta.4
v2.0.0.beta.10
v2.0.0.beta.11
v2.0.0.beta.12
v2.0.0.beta.13
v2.0.0.beta.14
v2.0.0.beta.15
v2.0.0.beta.2
v2.0.0.beta.3
v2.0.0.beta.5
v2.0.0.beta.6
v2.0.0.beta.7
v2.0.0.beta.8
v2.0.0.beta.9

> 10:43:45 directlink-android git:(develop)
$ git tag -l | grep v1.0.1.beta.4
v1.0.1.beta.4
```

Timestamp in EST time. After that, I started another build (https://www.bitrise.io/build/79c19e0278409a66) but it failed again with the same error. You will see that the build was started after the clone on my workstation, so I really don't see why it cannot find the tag.

It's really unclear why the tag cannot be retrieved. Seems as a cache problem but why? This happened once in the past for me and waiting a little bit and building again "fixed" the issue.

Matt

**Comment by viktorbenei** [comment]
Hi @maoueh 

Thanks for reporting this! Could you please report it through email, the onsite chat or on https://discuss.bitrise.io ?

This repository is not monitored for issues.

**Comment by maoueh** [comment]
@viktorbenei I propose that you guys add a `ISSUE_TEMPLATE.md` to the repository that would instructs users to create the issue at `https://discuss.bitrise.io` instead. 

I would have not created the issue having seen this :)

**Comment by viktorbenei** [comment]
Good point. Actually we turned off issues a while ago, but there were too many links for previous issues here, that's why we enabled it again.

I'll add the `ISSUE_TEMPLATE.md` now ;)

**Comment by viktorbenei** [comment]
Added the issue template, thanks for the feedback @maoueh and sorry for the inconvenience.
