### ISSUE TITLE
Loads of 404s when accessing devcenter.bitrise.io

### ISSUE THREAD

**Issue by cameronklein** [bitrise-io/bitrise.io#14]
On the "Pricing" page, under "FAQ," the first two buttons lead to a 404 error.

One can then access the devcenter home page with some address bar trickery, but many of the links on various help pages lead to 404 errors, as well.

Example: On "Getting Started with Bitrise," clicking "you can develop your own steps too" leads to 404.

**Comment by viktorbenei** [comment]
Ouch. We just moved our DevCenter recently to readme.io , I guess we were not thorough enough with the link testing..

Thanks for reporting @cameronklein , we'll fix it asap!

**Comment by bazscsa** [comment]
Bitrise.io wrong links to Devcenter:
Failed build - Found a glitch? Check out our…
App registration - Webhooks
Pricing page - documentation link, getting started with workflows link
Workflow editor - use your own step link, the other use your own step link, Code Security link, Base Build Environment link, on our devcenter link

**Comment by viktorbenei** [comment]
All should be fixed now. Once again, thank you for reporting @cameronklein !
