### ISSUE TITLE
Swift support build error from iTunes Connect

### ISSUE THREAD

**Issue by alcarvalho** [bitrise-io/bitrise.io#16]
After being able to submit the build to iTunes using the Shenzen deploy step, I got an email from iTunes Connect stating a problem with Swift Support. 

I am not sure on which step is the source of this error, so I am reporting it here.

>Dear developer,
>
>We have discovered one or more issues with your recent delivery for "Winnin". To process your delivery, the following issues must be corrected:
>
>**Invalid Swift Support** - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

**Comment by viktorbenei** [comment]
hi @alcarvalho - can you please send your build's logs ( the one you used for building the app for app store distribution ) in email? Without the logs it's really hard to say anything.

**Comment by viktorbenei** [comment]
This might also help @alcarvalho - http://stackoverflow.com/a/32685513/974381

**Comment by alcarvalho** [comment]
Sure, @viktorbenei! I have already checked that answer on StackOverflow and it does not reflect my reality. Our app is entirely in Swift and the build works when I build on my machine.

**Comment by viktorbenei** [comment]
This should be fixed in the latest Xcode Archive step. I'll close this issue, feel free to comment if you would still have problems and we'll re-open it.
