### ISSUE TITLE
Automatic workflow selection not working

### ISSUE THREAD

**Issue by jaffacake** [bitrise-io/bitrise.io#17]
I've created a workflow called feature/fastlane which corresponds to a branch in my repo. I've noticed that when pushing changes and starting a build directly from bitrise, the primary workflow is used, instead of feature/fastlane.

In order for it to work, I have to go into bitrise and use start a build and the advanced settings to manually select the workflow.

**Comment by birmacher** [comment]
Hi @jaffacake!

Can you please share your trigger map? You can find it when you click on the "Manage Workflow" button.

**Comment by viktorbenei** [comment]
Actually @jaffacake could you share it in the format you can see in the `bitrise.yml` mode / section (on the "Manage Workflows" page)?

**Comment by jaffacake** [comment]
---
format_version: 1.1.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
app:
  envs:
  - BITRISE_PROJECT_PATH: mf-ios-app.xcworkspace
    opts:
      is_expand: false
  - BITRISE_SCHEME: mf-ios-app-CI
trigger_map:
- pattern: "*"
  is_pull_request_allowed: true
  workflow: primary
workflows:
  primary:
    steps:
    - activate-ssh-key@3.0.2:
        title: Activate App SSH key
        inputs:
        - ssh_key_save_path: "$HOME/.ssh/steplib_ssh_step_id_rsa"
    - git-clone@3.0.0:
        outputs:
        - GIT_CLONE_COMMIT_HASH: 
          opts:
            title: Cloned git commit's commit hash
        - GIT_CLONE_COMMIT_MESSAGE_SUBJECT: 
          opts:
            title: Cloned git commit's message subject
        - GIT_CLONE_COMMIT_MESSAGE_BODY: 
          opts:
            title: Cloned git commit's message body
        - GIT_CLONE_COMMIT_AUTHOR_NAME: 
          opts:
            title: Cloned git commit's author name
        - GIT_CLONE_COMMIT_AUTHOR_EMAIL: 
          opts:
            title: Cloned git commit's author email address
        - GIT_CLONE_COMMIT_COMMITER_NAME: 
          opts:
            title: Cloned git commit's committer name
        - GIT_CLONE_COMMIT_COMMITER_EMAIL: 
          opts:
            title: Cloned git commit's committer email
    - cocoapods-install@1.0.3: {}
    - certificate-and-profile-installer@1.2.1: {}
    - select-xcode-version@2.2.0: {}
    - xcode-test@1.5.0:
        title: 'Xcode: Unit Test'
        inputs:
        - workdir: mf-ios-app
    - xcode-archive@1.2.0:
        title: 'Xcode: Create Archive'
        inputs:
        - workdir: mf-ios-app
        - output_dir: "${BITRISE_DEPLOY_DIR}"
        outputs:
        - BITRISE_IPA_PATH: 
          opts:
            title: The created .ipa file's path
        - BITRISE_DSYM_PATH: 
          opts:
            title: The created .dSYM.zip file's path
  feature/fastlane:
    steps:
    - activate-ssh-key@3.0.2:
        title: Activate App SSH key
        inputs:
        - ssh_key_save_path: "$HOME/.ssh/steplib_ssh_step_id_rsa"
    - git-clone@3.0.0:
        outputs:
        - GIT_CLONE_COMMIT_HASH: 
          opts:
            title: Cloned git commit's commit hash
        - GIT_CLONE_COMMIT_MESSAGE_SUBJECT: 
          opts:
            title: Cloned git commit's message subject
        - GIT_CLONE_COMMIT_MESSAGE_BODY: 
          opts:
            title: Cloned git commit's message body
        - GIT_CLONE_COMMIT_AUTHOR_NAME: 
          opts:
            title: Cloned git commit's author name
        - GIT_CLONE_COMMIT_AUTHOR_EMAIL: 
          opts:
            title: Cloned git commit's author email address
        - GIT_CLONE_COMMIT_COMMITER_NAME: 
          opts:
            title: Cloned git commit's committer name
        - GIT_CLONE_COMMIT_COMMITER_EMAIL: 
          opts:
            title: Cloned git commit's committer email
    - cocoapods-install@1.0.3: {}
    - certificate-and-profile-installer@1.2.1: {}
    - select-xcode-version@2.2.0: {}
    - xcode-archive@1.2.0:
        title: 'Xcode: Create Archive'
        inputs:
        - workdir: mf-ios-app
        - output_dir: "${BITRISE_DEPLOY_DIR}"
        outputs:
        - BITRISE_IPA_PATH: 
          opts:
            title: The created .ipa file's path
        - BITRISE_DSYM_PATH: 
          opts:
            title: The created .dSYM.zip file's path
    - script@1.1.0:
        inputs:
        - content: |-
            #!/bin/bash

            echo "BITRISE_IPA_PATH: $BITRISE_IPA_PATH"
            envman add --key PILOT_IPA --value "$BITRISE_IPA_PATH"
    - fastlane@2.0.0:
        inputs:
        - lane: beta
        - work_dir: mf-ios-app

**Comment by viktorbenei** [comment]
@jaffacake not sure why, but your `trigger_map` does not contain the required mapping.

It should be added automatically when you create a new workflow, we'll check this.

You can find a guide at http://devcenter.bitrise.io/v1.0/docs/lesson-6-pull-the-trigger-on-the-workflow about the `trigger_map`.

If you only want to use the `fastlane` workflow for the `feature/fastlane` branch then you should have a trigger map:

```
trigger_map:
- pattern: "feature/fastlane"
  is_pull_request_allowed: true
  workflow: fastlane
- pattern: "*"
  is_pull_request_allowed: true
  workflow: primary
```

You can set the `is_pull_request_allowed` property to `true` or `false`, depending on whether you want to allow this workflow to be selected for Pull Requests.

**Comment by viktorbenei** [comment]
Of course the `workflow` should match the actual workflow name, so if your workflow's name is `feature/fastlane` you should specify it as `workflow: feature/fastlane` - but in general it's better to use shorter workflow names and use the `pattern` property to select it.

**Comment by viktorbenei** [comment]
We made some revision on bitrise.io 's graphical Workflow editor, `trigger_map` entries should be automatically created & destroyed when you add / delete a workflow.
