### ISSUE TITLE
AppleTV Export Archive Failed

### ISSUE THREAD

**Issue by psiegPI** [bitrise-io/bitrise.io#18]
I am trying to build an AppleTV app, but get the following error on the archive step (.xcarchive' cannot be exported as IPA).  Is this an Apple bug or something on Bitrise?

** ARCHIVE SUCCEEDED **
set +v
 * embedded.mobileprovision: /Users/vagrant/deploy/******-AppleTV.xcarchive/Products/Applications/*****-AppleTV.app/embedded.mobileprovision
 (i) Found Profile Name for signing: *****-AppleTV-AppStore
#
# Use the Provisioning Profile name to export the IPA
xcodebuild -exportArchive \
	-exportFormat ipa \
	-archivePath "${archive_path}" \
	-exportPath "${ipa_path}" \
	-exportProvisioningProfile "${profile_name}"
--- xcodebuild: WARNING: -exportArchive without -exportOptionsPlist is deprecated
2015-10-27 14:18:09.240 xcodebuild[1937:9787] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-9077/IDEFoundation/Execution/Archiving/IDEArchivedApplication.m:148
Details:  Asked if we support packaging as a given format, but the platform is unknown: appletvos
Object:   
Method:   -supportsPackagingAsFormat:
Thread:   {number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
error: archive at path '/Users/vagrant/deploy/*****.xcarchive' cannot be exported as IPA
** EXPORT FAILED **

**Comment by viktorbenei** [comment]
Hi, 

Did you set your Xcode version to 7.1 (beta)? 

The default Xcode version is 7.0.1,which does not support tvOS

If you can't figure it out please send your build's log in email, and we'll have a look asap.

**Comment by psiegPI** [comment]
Hello,

I did select the beta and 7.1 beta options but still had the same results.
I attached the log.  Thanks!

On Tue, Oct 27, 2015 at 6:00 PM, Viktor Benei <notifications@github.com>
wrote:

> Hi,
>
> Did you set your Xcode version to 7.1 (beta)?
>
> The default Xcode version is 7.0.1,which does not support tvOS
>
> If you can't figure it out please send your build's log in email, and
> we'll have a look asap.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitrise-io/bitrise.io/issues/18#issuecomment-151658338>
> .
>



-- 

Peter Siegmann

Devops Engineer


Prolific Interactive

45 Main St., Suite 1006 | Brooklyn, NY 11201

o: 347.462.0990 | m: 516.425.2548 | prolificinteractive.com | @weareprolific
<http://www.twitter.com/weareprolific> | @psiegs
<https://twitter.com/psiegs>

**Comment by viktorbenei** [comment]
Did you attached the logs to your email? We can't see it.

**Comment by viktorbenei** [comment]
Please send your logs directly to letsconnect@bitrise.io, just to be sure we receive it.

**Comment by viktorbenei** [comment]
This should work now with the latest Xcode Archive step (`1.5.2`). I'll close this issue, but feel free to comment if you would still have this problem.
