### ISSUE TITLE
Poor performance for web app build view

### ISSUE THREAD

**Issue by scottrhoyt** [bitrise-io/bitrise.io#19]
Leaving the web app open on a build while it is running results in browser slowdowns and hangs. This seems to be related to the build log as it gets larger. As it is, this view is only useful after a build completes.

**Comment by viktorbenei** [comment]
Thanks for reporting @scottrhoyt - this is already on our list, we'll try to bump it's priority.

**Comment by scottrhoyt** [comment]
Thanks!

**Comment by viktorbenei** [comment]
Hi @scottrhoyt - we pushed a new version of the log viewer yesterday, and a couple of fixes today. The log viewer was completely rewritten, more optimized for live & larger logs. We'll most likely push a couple more optimizations, but in general it should now be a more pleasant experience to use it.

I'll close this issue, but feel free to re-open or add notes if you have any feedback!

**Comment by scottrhoyt** [comment]
Thanks!

On Thu, Dec 17, 2015 at 2:53 AM, Viktor Benei <notifications@github.com>
wrote:

> Closed #19 <https://github.com/bitrise-io/bitrise.io/issues/19>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitrise-io/bitrise.io/issues/19#event-494555054>.
>



-- 

[image: Wild Onion Labs] <http://wildonion.io/>

Scott Hoyt / CoFounder
708.704.6804/ scott@wildonion.io

Wild Onion Labs
http://wildonion.io

[image: Facebook] <https://www.facebook.com/scotthoyt> [image: Twitter]
<https://twitter.com/scotthoyt> [image: Linkedin]
<https://www.linkedin.com/in/scottrhoyt>

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Wild Onion Labs
LLC is not responsible for errors or omissions in this message and denies
any responsibility for any damage arising from the use of e-mail. Any
opinion and other statement contained in this message and any attachment
are solely those of the author and do not necessarily represent those of
the company.
