### ISSUE TITLE
iOS - fastlane: No codesigning identities found

### ISSUE THREAD

**Issue by bartonhammond** [bitrise-io/bitrise.io#20]
Log error:
> ❌  Code Sign error: No codesigning identities found: No codesigning identities (i.e. certificate and 
> private key pairs) that match the provisioning profile specified in your build settings (“Bartons phone, 
> Fireball, Distribution”) were found.

But further up log:

> 1 identity imported.
> set-keychain-settings "-lut" "72000" "/Users/vagrant/Library/Keychains/login.keychain"
list-keychains
> list-keychains "-s" "/Users/vagrant/Library/Keychains/login.keychain" 
> "/Library/Keychains/System.keychain" "/Users/vagrant/Library/Keychains/login.keychain"
> default-keychain "-s" "/Users/vagrant/Library/Keychains/login.keychain"
> unlock-keychain "-p" "vagrant" "/Users/vagrant/Library/Keychains/login.keychain"
> Installed certificate: iPhone Distribution: Barton Hammond (BJW5E7FWWV)
> => Available iOS & Mac certificates:
> 
> iPhone Distribution: Barton Hammond (BJW5E7FWWV)
> 
> => Downloading & installing Provisioning Profile(s) ...
> (i) Provided Provisioning Profile count: 1
> ==> Downloading provisioning profile: 1/1
>===> Installing provisioning profile
>====> Installed Profile UUID: a595cb34-961f-480a-bede-2e3921c8c017
>====> Moving it to: /Users/vagrant/Library/MobileDevice/Provisioning Profiles/a595cb34-961f-480a->bede-2e3921c8c017.mobileprovision

The provision profile **a595cb34-961f-480a->bede-2e3921c8c017** is  in text of the provision:
```
	<string>Barton Hammond</string>
	<key>TimeToLive</key>
	<integer>364</integer>
	<key>UUID</key>
	<string>a595cb34-961f-480a-bede-2e3921c8c017</string>
	<key>Version</key>
	<integer>1</integer>
```
Xcode project is configured

<img width="664" alt="screen shot 2015-12-10 at 7 28 05 pm" src="https://cloud.githubusercontent.com/assets/1282364/11733561/4a02bb5c-9f74-11e5-8a87-7471efa95d3f.png">

My firelane:
```
lane :beta do
    increment_build_number(
      xcodeproj: './ios/fireball.xcodeproj'
    )

    gym(
      scheme: 'fireball',
      project: './ios/fireball.xcodeproj'
    )

end
```

I followed these instructions: [http://devcenter.bitrise.io/docs/provprofile-cert-export](http://devcenter.bitrise.io/docs/provprofile-cert-export)

**Comment by bartonhammond** [comment]
I tried this too:
```
    gym(
      codesigning_identity: $BITRISE_CODE_SIGN_IDENTITY,
      provisioning_profile_path: '/Users/vagrant/Library/MobileDevice/Provisioning Profiles/a595cb34-961f-480a-bede-2e3921c8c017.mobileprovision',
      scheme: 'fireball',
      project: './ios/fireball.xcodeproj'
    )
```
and same message...

**Comment by viktorbenei** [comment]
In Ruby you have to use `ENV[...]` to get environment variables.

`codesigning_identity: $BITRISE_CODE_SIGN_IDENTITY,` -> `codesigning_identity: ENV['BITRISE_CODE_SIGN_IDENTITY'],`

**Comment by bartonhammond** [comment]
Right, I realized that late last night.
So then I tried this:

```
   ENV['PROFILE_UUID'] = ENV['BITRISE_PROVISIONING_PROFILE_ID']

    gym(
      codesigning_identity: ENV['BITRISE_CODE_SIGN_IDENTITY'],
      scheme: 'fireball',
      project: './ios/fireball.xcodeproj',
      verbose: true
    )
```

but still same error

```
             
    ENV["PROFILE_UUID"] = 'a595cb34-961f-480a-bede-2e3921c8c017' #$BITRISE_PROVISIONING_PROFILE_ID

    gym(
      codesigning_identity: 'iPhone Distribution: Barton Hammond (BJW5E7FWWV)', #$BITRISE_CODE_SIGN_IDENTITY,
      scheme: 'fireball',
      project: './ios/fireball.xcodeproj',
      verbose: true
    )
```
same problem ..
```
❌  Code Sign error: No codesigning identities found: No codesigning identities (i.e. certificate and private key pairs) that match the provisioning profile specified in your build settings (“Bartons phone, Fireball, Distribution”) were found.
```

**Comment by viktorbenei** [comment]
Can it be that you have a conflicting code signing settings in your Xcode Project? Not sure how `gym` handles if you pass in an Identity but that's not the one set in your Xcode Project.

You might want to ask this in `gym`'s or `fastlane`'s GitHub issues instead, I don't think this would be related to bitrise, it's more likely that you have to set an environment variable or another option in your `gym` config or something like that.

**Comment by bartonhammond** [comment]
Ok - will do

**Comment by viktorbenei** [comment]
Let us know if we can help, but we double-checked the codes/logs you included and there's nothing wrong with it what would be related to bitrise.

**Comment by bartonhammond** [comment]
Got it.  Opened issue with Fastlane:
https://github.com/fastlane/gym/issues/160
