### ISSUE TITLE
Android beta - need node/npm install

### ISSUE THREAD

**Issue by bartonhammond** [bitrise-io/bitrise.io#21]
Building w/ React-Native requires npm

```
mp/bitrise258180480/step_src/._script_cont: line 3: npm: command not found
```

**Comment by viktorbenei** [comment]
NPM is not pre-installed on the Android stack. You can see everything what's pre-installed here: https://github.com/bitrise-docker/bitrise-base/blob/master/Dockerfile - The Android docker image uses this base docker image, and just adds Android specific components.

**Comment by viktorbenei** [comment]
Android docs: http://devcenter.bitrise.io/docs/android-beta - specifically, about the environment: http://devcenter.bitrise.io/v1.0/docs/android-environment-whats-pre-installed

**Comment by bartonhammond** [comment]
I understood that it didn't, I did read the docs.

So I shall install node then.

**Comment by viktorbenei** [comment]
You can also PR into the Docker image, to have it pre-installed, but given that NodeJS updates quite frequently lately I'm not sure whether we should preinstall a version which might get outdated quite quickly..
