### ISSUE TITLE
Add Release Notes to BitRise Deploy.

### ISSUE THREAD

**Issue by scottrhoyt** [bitrise-io/bitrise.io#22]

**Comment by viktorbenei** [comment]
You can find the release notes in the releases section of GitHub,  for every step we maintain.  Just open the GitHub page of the step and click on releases 😊

**Comment by viktorbenei** [comment]
Reading it again, did you mean release notes attached to a build?

**Comment by scottrhoyt** [comment]
Yeah, sorry. I meant on the BitRise deploy step for iOS.

**Comment by viktorbenei** [comment]
What would you like to see exactly? Where/how should be the notes delivered?

**Comment by scottrhoyt** [comment]
Again, sorry, It's a rushed day so I haven't supplied many details. Basically we are using BitRise to handle continuous delivery for us on development, qa, and production branches.  Our testers receive all three of these kinds of builds. It would be nice to have a way to indicate what sort of build they are being notified of. Previously we resorted to embedding that information in version number or build number where it doesn't play well with other parts of the workflow: setting build number to git commit number, auto setting environment based off of branch name, Apple's agvtool, or submissions to iTunes Connect. In addition, it would be nice to have a place to indicate what to test and we can even just auto-populate that from git commit messages.

Having Release Notes attached to the deploy action would at least give a location for people to implement these sorts of flows. Many deployment-focused services (e.g. HockeyApp, TestFairy) have a similar feature. Some go further to allow setting the release type, which would be really nice as well.

**Comment by viktorbenei** [comment]
I agree, this is definitely something we would like to do in the future. The best would be if you could create a UserVoice feature request, as that's treated like a priority backlog. I thought we had a similar request before, but I can't find any, so feel free to create a new one: https://bitrise.uservoice.com
