### ISSUE TITLE
Compiling Android Glass APK fails on finding GDK

### ISSUE THREAD

**Issue by hijklmno** [bitrise-io/bitrise.io#24]
Hi Bitrise,

I'm having an issue building my GDK app. The issue is:

failed to find target with hash string 'Google Inc.:Glass Development Kit Preview:19' in: /opt/android-sdk-linux

I'm guessing the /opt/android-sdk-linux is a folder where it contains all the Android SDKs? Is it right to assume that the GDK should also be there? 

I have tried a fix [here](http://stackoverflow.com/questions/20107002/google-glass-gdk-with-android-studio), which adds the gdk.jar into the build.gradle as a dependecy, but it doesn't seem to know where to find it. Should I something with the environment variables?

Thank you.

**Comment by viktorbenei** [comment]
Hi,

Does the GDK require an additional component to be pre-installed?
You can find all the pre-install android packages here: https://github.com/bitrise-docker/android/blob/master/Dockerfile#L28

If you want to install additional components you can do that with a Script step, or with the "Update Android SDK" (https://github.com/guitcastro/steps-update-sdk) step. Note: this step is not maintained by us, was contributed by one of our users.

**Comment by hijklmno** [comment]
Hi vicktorbenei,

Sorry for the delay in response, and thanks for your help!

I took your advice and was able to use the "Update Android SDK" step to install the GDK, though I had to pass the variable "add-on" to the "system images" variable and download all the other unnecessary add-ons. 

Thank you for your help and quick response!

**Comment by viktorbenei** [comment]
Thanks for the response! Can you share which add-ons you had to install? Might be useful for someone else in the future.

**Comment by hijklmno** [comment]
Yep, the add-on was the GDK. (:

**Comment by viktorbenei** [comment]
Ohh, I thought there were other ones you had to install ;) Thanks for reporting! :)
