### ISSUE TITLE
xcpretty eats fatal error message

### ISSUE THREAD

**Issue by philippelatulippe** [bitrise-io/bitrise.io#27]
xcpretty didn't output anything after my first build on bitrise failed. After disabling xcpretty, the error was:

    xcodebuild: error: Scheme <scheme> is not currently configured for the test action.

If I run the latest xcpretty locally the error is shown correctly, so maybe it's just a matter of upgrading it.

**Comment by viktorbenei** [comment]
Thanks for reporting! We also saw cases when Xcode's output includes the error, but not `xcpretty`'s output. We'll try to find a solution for these issues (like attaching the full, raw xcodebuild output to your build as an artifact).

> If I run the latest xcpretty locally the error is shown correctly

That's strange, the latest xcpretty version (0.2.2) was released last December - https://github.com/supermarin/xcpretty/releases - and all of our Xcode 7 VMs have this version preinstalled (https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xcode-7.3-beta.log#L50 & https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xcode-7.2.log#L49).

**Comment by philippelatulippe** [comment]
That's strange. I tried the build a few times on bitrise and the error was never shown. After turning of xcpretty it was then shown.

**Comment by viktorbenei** [comment]
Sure, you're right, we saw that too. The strange thing is that in our case, when we ran the same command locally (not on bitrise.io) with `xcpretty` we got the same result, no error messages included, only in the raw `xcodebuild` output.

**Comment by viktorbenei** [comment]
The solution for now is to use the `xcodebuild` as the Output Tool option. We'll keep updating `xcpretty`, it's a known and reported issue there, hopefully they'll fix it in the near future.

**Comment by LMojica** [comment]
Did this ever get fixed? I'm on version 0.2.4 and xcpretty ignore any test failures that begin with "fatal error".
