### ISSUE TITLE
Can't build project without tests

### ISSUE THREAD

**Issue by philippelatulippe** [bitrise-io/bitrise.io#28]
My project doesn't have tests yet. xcodebuild immediately fails with the error message:

> xcodebuild: error: Scheme X is not currently configured for the test action.

That's because the build and test steps are run in the same command. It's easy to work around this problem by setting up the scheme properly, but still a bump in the road.

**Comment by viktorbenei** [comment]
But you got this error when you tried to run the Xcode Test step, right? I think it's completely reasonable to fail with this error when you run Xcode Test but your project is not configured for tests. Also, this is not bitrise.io related, if you try to run Test in `Xcode.app` on a project which doesn't have tests configured it'll fail with the same error - we use Xcode's Command Line Tools directly, no custom, bitrise.io specific logic  here. If Xcode fails with this error then the related step with fail with this error.

**Comment by philippelatulippe** [comment]
That's true, I would expect the Test step to fail in this case. But the bitrise.io logic that auto-configures the job (which is otherwise excellent) added this step even though my project isn't configured for tests. I think it'd make the first-time experience nicer to detect that. :) Additionally it was a bit confusing that there was no separate "build" step, just a step for testing that actually ran the build too.

**Comment by viktorbenei** [comment]
Thanks for the clarification, I think you're right. I added this to our "things to discuss" list, we have quite a few things we'll change in the near future, related to the on-boarding / setup experience ;)
