### ISSUE TITLE
Unable to configure correct $PRODUCT_BUNDLE_IDENTIFIER in xcode-archive step

### ISSUE THREAD

**Issue by shamikagasc** [bitrise-io/bitrise.io#29]
Xcode archive step fails when you upgrade your project to use the recommended settings for iOS 9. This is because there xcodebuild is not passed the correct bundleidentifier parameter. Are there any plans to fix this soon?
reference step : https://github.com/bitrise-io/steps-xcode-archive

**Comment by viktorbenei** [comment]
Can you please send the build log in email (https://www.bitrise.io/contact)?

> This is because there xcodebuild is not passed the correct bundleidentifier parameter

We don't set any bundle ID parameter. You can see the full `xcodebuild` command in the build log, after a `=> Archive command:` line (https://github.com/bitrise-io/steps-xcode-archive/blob/master/step.sh#L182).

**Comment by viktorbenei** [comment]
P.S.: I closed this ticket because without any logs it's impossible to tell what the issue is.

**Comment by shamikagasc** [comment]
Thanks @viktorbenei , I have attached a sample failure build log in an email to letsconnect@bitrise.io referencing this issue. I hope we can get a resolution on this soon.
