### ISSUE TITLE
GitHub Triggered builds are not syncing correctly

### ISSUE THREAD

**Issue by gabosgab** [bitrise-io/bitrise.io#30]
I'm seeing issues where the build is building successfully, however the source code it's building from is rather old.  Can you please check that pulls are working correctly?

Project: https://www.bitrise.io/app/c4fc0eb825544c14

**Comment by viktorbenei** [comment]
Can you please send this in email to letsconnect@bitrise.io, and attach the build log to the email? Please also describe why do you think there's an issue - like "the build had a commit hash AAAA while bitrise built the commit with hash BBBB" (you can find the commit hash in the Git Clone step's log).
