### ISSUE TITLE
Cocoapods Install Error

### ISSUE THREAD

**Issue by kpavankotesh** [bitrise-io/bitrise.io#34]
| 🚫  | cocoapods-install@1.1.0 (exit code: 1)                       | 72 sec   |

I am using bitrise to deliver iOS application and in the recent past there were lot of instances I faced this build failure due to cocoapods install issue. Is this due to Github outage or some issue on your side. Can you please clarify and if possible fix it?

**Comment by viktorbenei** [comment]
Hi, most likely GitHub or another service. From the log you shared it's not clear at all - it just means that the 1.1.0 version of the step failed, the exit code does not have any special meaning.

Please share the rest of the step's log if you want us to have a look - if it includes private information you can share it in email ( https://www.bitrise.io/contact ).
