### ISSUE TITLE
xcode-archive 1.7.1 step is Swift 2.2 incompatible

### ISSUE THREAD

**Issue by shamikagasc** [bitrise-io/bitrise.io#35]
The step fails when using new syntax such as `#selector`

**Comment by viktorbenei** [comment]
Did you select the Xcode 7.3 stack? - http://blog.bitrise.io/2016/03/22/xcode-7-3-final-is-now-available.html

**Comment by shamikagasc** [comment]
I am unable to find the `settings` tab at the bottom on bitrise.io....

**Comment by viktorbenei** [comment]
It's available if you're an administrator or owner in the app:
<img width="1219" alt="screen_shot_2016-04-19_at_20_07_18" src="https://cloud.githubusercontent.com/assets/430618/14650120/89be2f6c-066a-11e6-83ff-a746a84e19a5.png">

**Comment by shamikagasc** [comment]
No i found it, all im saying is it was not visible to me on `https://www.bitrise.io/dashboard` , I had to click into the app to see the UI you just posted, and Im aware that this is very minor feedback, but I thought I'd just let you know anyway :)

**Comment by viktorbenei** [comment]
But that's the point - you can select different stacks & versions for every app ;) So we can't present the option on the Dashboard, you also have to select an app - and the Stack you select there will be used for that specific app.

Maybe some kind of icon / indicator could be used on the Dashboard though..

**Comment by shamikagasc** [comment]
<img width="1037" alt="screen shot 2016-04-19 at 11 17 45 am" src="https://cloud.githubusercontent.com/assets/14208579/14650379/6ecbcb6e-0620-11e6-9a8d-8378b4c2ac74.png">

I think your UI is fine, the blogpost was a bit confusing

**Comment by shamikagasc** [comment]
Never mind, I misread it, I apologize

**Comment by shamikagasc** [comment]
Thanks for the quick turn around, selecting the new xcode stack helped

**Comment by viktorbenei** [comment]
I see why you might missed the "your app" part - we'll change the text, to highlight it better!

**Comment by viktorbenei** [comment]
We did highlight the "open your app" part, the change will be out soon on the blog!

**Comment by shamikagasc** [comment]
👍
