### ISSUE TITLE
Builds row got duplicated 

### ISSUE THREAD

**Issue by dumoko** [bitrise-io/bitrise.io#36]
What i did:
I had the Builds page open while doing stuff in other tabs. I basically just clicked the tab again to see how the builds are going and noticed this:
<img width="1410" alt="screenshot 2016-05-10 12 28 33" src="https://cloud.githubusercontent.com/assets/457094/15141911/2433fef0-16ab-11e6-90c3-6c5b4fa36db7.png">

The first row seems like a duplicate of the 4th one.
As can be seen it shows no percent, and when clicked leads here:
<img width="336" alt="screenshot 2016-05-10 12 31 16" src="https://cloud.githubusercontent.com/assets/457094/15141913/266327f0-16ab-11e6-96de-bd5bc02e4d3a.png">

Refreshing the page did remove the "extra" build.

Hope this helps!

**Comment by viktorbenei** [comment]
We already have a related internal bug ticket for this issue, so I'll close it here and add the details to the existing ticket.

Thanks for reporting and for the details! It'll help us a lot to fix it! ;)
