### ISSUE TITLE
Tests failing in android because of headless emulator mode.

### ISSUE THREAD

**Issue by prabintim** [bitrise-io/bitrise.io#37]
I have some tests that are failing most likely because the emulator is running in headless mode. Tests such as launching phone dialer, opening app from Apps menu are failing. It would be nice to have option to set -no-window mode manually in the workflow.

Error:
```
dialer_opens_when_call_for_assistance_button_is_pressed[MY_EMU(AVD) - 4.4.4] FAILED 
	android.support.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
```

**Comment by viktorbenei** [comment]
Are you sure that this is caused by the `-no-window` flag/mode?

**Comment by prabintim** [comment]
Tried it on my local emulator and that does not seem to an issue.

**Comment by samblackmore** [comment]
I'm getting this same issue. I need to create the emulator with `-no-window` in order to run inside a Docker container. My test is passing when the emulator has a window in Android Studio.

**Comment by viktorbenei** [comment]
@prabintim as you closed this issue - can you please share what was the solution?

**Comment by prabintim** [comment]
@viktorbenei One of my tests was causing crash. That's why the warning was about Activity not being in Resumed state.

**Comment by viktorbenei** [comment]
Makes sense - thanks for sharing! :)
