### ISSUE TITLE
Build stops at "Touching MyProject_Tests.xctest"

### ISSUE THREAD

**Issue by haifengkao** [bitrise-io/bitrise.io#43]
It is similar to https://github.com/travis-ci/travis-ci/issues/5020

**Comment by viktorbenei** [comment]
Hi,

You can find a list of possible issues & solutions for this error at: https://bitrise-io.github.io/devcenter/ios/known-xcode-issues/#xcode-unit-test-fails-without-any-error-with-exit-code-65

Also, please create issue tickets on the Steps' GitHub page, not in this one. You can find the issue tracker link of every step in the build logs.
