### ISSUE TITLE
Multiple workflows chain executed not overriding env vars

### ISSUE THREAD

**Issue by Reedyuk** [bitrise-io/bitrise.io#44]
Hi,
I have a workflow that calls the git clone method multiple times, I wanted to pull that git clone into a separate folder, so i override the $BITRISE_SOURCE_DIR
The problem i get is that when i executed the second workflow, it doesn't override the environment variable with the new bitrise source directory.
I have attached a bitrise config file that demonstrates the error(you might need to use an iOS project, or atleast remove a step for plist injection).

If you execute Testing_Git_Clone_Master, this first calls Testing_Git_Clone, we use the default source directory, then after that has finished we call Testing_Git_Clone_2, this overrides the environment variable, but when the git clone step is executed, it does not inherit the new location.

Thanks
Andrew.

[bitrise_fail.yml.zip](https://github.com/bitrise-io/bitrise.io/files/331625/bitrise_fail.yml.zip)

**Comment by viktorbenei** [comment]
I might be wrong, but can't see: what should switch the dir? The `git::https://github.com/Reedyuk/steps-secure-add-path.git@master` step?

If you want to switch working directory during the build you should use the `change-workdir` step ;)

**Comment by Reedyuk** [comment]
Yes, you were correct, thanks
