### ISSUE TITLE
Rolling builds

### ISSUE THREAD

**Issue by jayvdb** [bitrise-io/bitrise.io#47]
Appveyor has the option of skipping builds for commits that are stale.

"Whenever you do a new commit to the same branch OR pull request all current **queued**/running builds (preferably only queued, but not yet running ones) for that branch or PR are cancelled and the new one is queued."
https://www.appveyor.com/docs/build-configuration#rolling-builds

This is very helpful for open source projects to avoid lots of little commits eating into the 200 build limit.

**Comment by viktorbenei** [comment]
Awesome idea! Make sure that you vote on it here, on GitHub ;)

**Comment by viktorbenei** [comment]
Hi,

Could you add a bit more description? Just so that it's clear for others too what this is about - can help you get more votes too ;)

**Comment by jayvdb** [comment]
My reason for requesting this is I run a training program @besutkode for high school students, most who are using git for the first time. For the first few exercises I let them commit like crazy in a shared private repo, and they hit the 200 build limit really quickly. Only in the third activity do I teach them commit cleanliness, after they are already used to the git basics, and have shown competency in coding.

**Comment by viktorbenei** [comment]
Thanks for the details - I made an edit in your original description, just to highlight that this would not abort running builds, only queued ones.

**Comment by jayvdb** [comment]
For bitrise, which has a limit on the number of builds, it wouldnt be semsible to kill a running build as it has already decremented the number of free builds - may as well let it run to completion.

**Comment by viktorbenei** [comment]
As well as, this can prevent the situation when during a busy day your team continuously push new commits, which could lead to no checks for a long time if it'd always abort the running build.

**Comment by bootstraponline** [comment]
> (I'd definitely prefer a system which does not abort running builds

The entire point of this feature is to abort running builds, to reclaim the executors for the latest commits.

**Comment by brentleyjones** [comment]
I think a default could be to skip queued builds. I personally, by default, wouldn't want the system to kill an already executing build.

**Comment by bootstraponline** [comment]
I don't mind as long as there an option. There's no point to letting a build execute if we don't care about the build.

**Comment by brentleyjones** [comment]
I agree. For me, all builds on master (maybe even queued ones?) I would want to build. In a pull request I would want to kill all, even active ones, since I only care about the latest code.

**Comment by bootstraponline** [comment]
Sounds good.

**Comment by jayvdb** [comment]
Perhaps a way to move forward is to have an binary option for bitrise to kill all (queued and running) stale builds, except on a set of excluded branches, with `master` as the default excluded branch. (and treat PR's as a separate branch for this purpose)

That should make 80% of people happy ;-)

Additional configuration, for the other 20%, of when to kill stale builds on `master` and other important branches could then be deferred to another enhancement, which will be tricker to get right.

**Comment by viktorbenei** [comment]
Sounds good, now we "just" have to figure out a way to make this configuration as easy and straight forward to use as possible, especially because misconfiguration could cause quite bad results (e.g. a deployment gets aborted).

**Comment by bootstraponline** [comment]
> Sounds good, now we "just" have to figure out a way to make this configuration as easy and straight forward to use as possible,

I think for the PR use case, a toggle that aborts old builds (disabled by default) when new commits are pushed is simple enough. It's the non-PR use case that's more complex.

**Comment by viktorbenei** [comment]
This issue was moved to https://discuss.bitrise.io/t/rolling-builds/150
