### ISSUE TITLE
Skip builds based on list of files modified

### ISSUE THREAD

**Issue by jayvdb** [bitrise-io/bitrise.io#48]
It would be very helpful to be able to skip builds when the modified files all match defined path/glob/etc.

This would especially help open source projects that are limited to 200 builds. That sounds like a lot, but it can quickly be used up if someone is doing lots of small commits, and completely useless if those commits are documentation (`.md`) only (the Github web UI edit functionality is ... too easy ...).

Identifying the files modified requires a clone of the repository to inspect the commit contents.  While this is still 'work' being done by bitrise, it less work than starting the container and running arbitrary commands in that container.  It can be optimised by caching the clone between builds, with an early expiration as commits that are further apart are more likely to needing a build.

**Comment by viktorbenei** [comment]
Thanks for the feature request, don't forget to vote on it here on GitHub! ;)

**Comment by viktorbenei** [comment]
This issue was moved to https://discuss.bitrise.io/t/skip-builds-based-on-list-of-files-modified/153
