### ISSUE TITLE
Allow Xcode testing step for multiple devices/operating systems

### ISSUE THREAD

**Issue by EPICAPPSLTD** [bitrise-io/bitrise.io#49]
When adding a testing step for Xcode, it would be great if I could specify a test suit for multiple devices and multiple operating system versions, instead of creating a separate testing step for each device/OS combo. With regards to the system versions, you could even support smart filters where a string like: ">9.0" will run your tests on every available OS greater than 9.0.

**Comment by viktorbenei** [comment]
Thanks for the feature request - don't forget to vote on it here, on GitHub! ;)

**Comment by viktorbenei** [comment]
Marked with `help wanted`, as this can be contributed by anyone, in the https://github.com/bitrise-io/steps-xcode-test repository.

**Comment by viktorbenei** [comment]
This issue was moved to https://discuss.bitrise.io/t/allow-xcode-testing-step-for-multiple-devices-operating-systems/147
