### ISSUE TITLE
Add support for Bitbucket Server webhook format

### ISSUE THREAD

**Issue by EPICAPPSLTD** [bitrise-io/bitrise.io#50]
Currently you cannot setup a webhook with Bitbucket Server, even though you have support for Bitbucket.org, which creates an issue when trying to get builds to trigger after a push to a repository.

**Comment by viktorbenei** [comment]
Thanks for the feature request - don't forget to vote on it here, on GitHub! ;)

**Comment by viktorbenei** [comment]
Marked with `help wanted`, as this can be contributed by anyone, into the https://github.com/bitrise-io/bitrise-webhooks repository. Once it's accepted there it will be available on hooks.bitrise.io too.

**Comment by ialmetwally** [comment]
any plan or timeline for this? I'm using bitbucket server and would like to trigger builds only after pull requests are approved.

**Comment by viktorbenei** [comment]
@ialmetwally no ETA yet, but if you have the time, feel free to send a Pull Request to https://github.com/bitrise-io/bitrise-webhooks - the README should include all the information for the PR

**Comment by viktorbenei** [comment]
Closing this ticket here - moved to https://discuss.bitrise.io/t/add-support-for-bitbucket-server-webhook-format/25

**Comment by ialmetwally** [comment]
@viktorbenei I'm planning to create a web hook for bitbucket server that integrates with [Pull Request notifier Addon](https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket).

So far I've added a new hook that works exactly like bitbucketv2 but only changed the url to work with bitbucket server.

Then deployed this on heroku, but I don't know how to test it with bitrise.io, should I just rely on unit tests, then submit a pull request, then you can integrate it with bitrisie.io? or there is another way to test it?

**Comment by viktorbenei** [comment]
Wow, that's awesome @ialmetwally !

The easiest way to test a new webhook, if you have it deployed to a Heroku dyno for example, is to:

1. open your app on [bitrise.io](https://www.bitrise.io)
1. go to the `Code` tab
1. copy the webhook URL from there
1. replace the host (hooks.bitrise.io) with the host of your Heroku app (asdf.herokuapp.com/h/...)

Note: make sure that the `/h/xxx` part points to the endpoint you added, e.g. `/h/bitbucketserver/`.

If you have any questions, just let us know! ;)

**Comment by viktorbenei** [comment]
This section of the readme should help you to get started: https://github.com/bitrise-io/bitrise-webhooks#deploy-to-heroku
