### ISSUE TITLE
Remove "on Bitrise" from Github status notifications

### ISSUE THREAD

**Issue by kkaefer** [bitrise-io/bitrise.io#54]
When looking at our CI build status on Github, I frequently see something like this:

![mapbox-gl-native 2016-08-01 11-48-32](https://cloud.githubusercontent.com/assets/52399/17290365/5e43eb54-57de-11e6-8e1e-be37d6ae72d4.png)

In most cases, the full name of our build is truncated because the string is already too long. I propose removing the "on Bitrise" part to make room for the full names. Both the icon and the build ID (which contains `bitrise`) already show that this build is provided by Bitrise.

**Comment by viktorbenei** [comment]
Awesome idea, thanks for the feature request! Don't forget to vote on it here, on GitHub! ;)

**Comment by kkaefer** [comment]
Alternatively, the IDs could change to something that includes the name, e.g.
`ci/bitrise/gl-native-qt5/push`, with `gl-native-qt5` being a sluggified version of the actual name.

**Comment by viktorbenei** [comment]
@kkaefer that could work, but there's no restriction about how you name your apps, so you can name two apps/projects the same way. The included slug is meant to provide a unique identification for the project.

**Comment by kkaefer** [comment]
The duplicate `on Bitrise` string is still obscuring the names of our builds. Any way to have this implemented as described in the original issue? Is there more discussion needed?

**Comment by viktorbenei** [comment]
actually, as `/bitrise/` is in the ID anyway, we could remove it from the text, I think

@birmacher WDYT?

**Comment by kkaefer** [comment]
That's what I'm suggesting, yeah 😉

**Comment by viktorbenei** [comment]
Will be deployed today ;)

**Comment by viktorbenei** [comment]
Deployed! :rocket: 

Thanks for the feature request and for the discussion / details! ;)
