### ISSUE TITLE
Wrong branch shown in build list and on build details

### ISSUE THREAD

**Issue by hdodenhof** [bitrise-io/bitrise.io#65]
For our release builds I created a workflow that clones and builds `master` regardless of what has been set in the build configuration dialog by hardcoding `master` as "Git Branch to clone" and leaving the inputs for commit / tag / PR empty in the "Git Clone Repository" step.

Looking at the build logs this seems to work perfectly:
```
  => git "init"
  => git "remote" "add" "origin" "git@github.com:[...]"
  => git "fetch"
  => git "checkout" "master"
  => git "submodule" "update" "--init" "--recursive"
```

Problem is that in the build list and on the build details page the branch shown for that build is `develop` instead of `master`.

**Comment by viktorbenei** [comment]
The info you see on the Web UI is about what triggered the build. You're free to do anything with those values - e.g. overwrite as you did - but the web UI is meant to present the trigger infos.

If you don't want to build the `develop` branch you should use the Triggers / `trigger_map` feature instead.

**Comment by hdodenhof** [comment]
Well, I triggered the build manually and didn't input anything except the workflow in the build configuration dialog. If the Web UI is about what triggered the build shouldn't it then be showing something indicating that the build was started manually?

**Comment by viktorbenei** [comment]
If you don't specify any branch, the build is started with the default branch, the one you can set in the app's Settings (tab)

**Comment by viktorbenei** [comment]
Manual builds register the parameters you provide - e.g. if you provide a commit hash that will be presented on the web UI too, but if you don't then it won't.

**Comment by viktorbenei** [comment]
> Well, I triggered the build manually and didn't input anything except the workflow in the build configuration dialog.

The branch name is auto-filled with the default / primary branch, the one from Settings (tab)

**Comment by hdodenhof** [comment]
While I do get the reasoning behing falling back to the default branch if nothing is set (I cleared the auto-filled default), I find the behavior a little confusing in this specific case - I was actually pretty worried I just build and pushed a release from the develop branch.

**Comment by viktorbenei** [comment]
We'll definitely discuss this internally, I have to admit this is quite an edge case :)

**Comment by hdodenhof** [comment]
Cool, thanks! :)
