### ISSUE TITLE
Automatically re-build open pull request when target branch is updated (e.g. another Pull Request is merged)

### ISSUE THREAD

**Issue by jhassine** [bitrise-io/bitrise.io#74]
If you have a branch, e.g. `master`, which is the target of the PRs, then any change on `master` should trigger a new build for **every** open PRs.

Use case:
- you have 5 open Pull Requests
- you merge a Pull Request
- the remaining 4 open Pull Requests should be re-tested, for a refreshed Pull Request status (allow/don't allow merge)

But in general, if e.g. `master` changes (even if by a code push directly on `master`) every open Pull Request should be re-tested / re-built (the ones which target `master`)

**Comment by viktorbenei** [comment]
Thanks for the feature request @jhassine !
I added a bit more detail to the description, to provide a better context for others.

_P.S.: don't forget to vote on it here, on GitHub ;)_

**Comment by viktorbenei** [comment]
This issue was moved to https://discuss.bitrise.io/t/automatically-re-build-open-pull-request-when-target-branch-is-updated-e-g-another-pull-request-is-merged/148
