### ISSUE TITLE
gradle version failure 

### ISSUE THREAD

**Issue by vrangasayee** [bitrise-io/bitrise.io#77]
# Bitrise Build Issue Report template
https://www.bitrise.io/build/66eaec6736dba6b7
## Description of the issue

* Where:
Build file '/bitrise/src/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 2.14.1. Current version is 2.10. If using the gradle wrapper, try editing the distributionUrl in /bitrise/src/gradle/wrapper/gradle-wrapper.properties to gradle-2.14.1-all.zip

## Environment:

Bitrise.io
- If on Bitrise.io: Current stack: Android & Docker, on Ubuntu 16.04 (pre-installed tools)
Select new stack
- If not on Bitrise.io: on what operating system? (Plus any other information you can share)

Which build Step causes the issue and which version of the step?

## Reproducibility

- Does a "Rebuild" help? No
- Does a rebuild without caches help? NA
- If it's an issue which happens sporadically, what's the frequency? 100% builds
- Does upgrading the build Step to the latest version help? how do i do this?
- When did the issue start? yesterday (10/12/2016)

### Linux/Android stack builds

- Can it be reproduced by running the build locally with Docker (using the same docker images we use on bitrise.io), after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC) and running the build from there? (Related guide: http://blog.bitrise.io/2016/08/08/debug-your-android-linux-builds-locally-with-docker.html )

### All / other stacks

- Can it be reproduced by running the build locally with our CLI ( https://www.bitrise.io/cli ), after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC) and running the build from there with the CLI?

## Build log

Please attach the build log (you can download the build log from the build's page, once the build is finished, using the "Download log" button - floating at the bottom right corner of the log viewer).

**Comment by viktorbenei** [comment]
please do not send this here, and please fill out the whole template / answer all the questions - send it in email or through the onsite chat

**Comment by viktorbenei** [comment]
from the error message most likely the top results here can help: https://www.google.com/?gfe_rd=cr&ei=PQQAWPDYB-rv8Aevxb9Q&gws_rd=cr&fg=1#safe=off&q=Minimum+supported+Gradle+version+is+2.14.1.+Current+version+is+2.10.
