### ISSUE TITLE
Provide write-only Secret Env Vars on bitrise.io (don't show the value on the Web UI after it's set)

### ISSUE THREAD

**Issue by kartikbb** [bitrise-io/bitrise.io#80]
As of now, all admins can see the apple account username and password in "Deploy to ItunnesConnect" step which is big security issue. 
Ideally, the password should not be displayed in plain text in the workflow editor. It should be masked.

**Comment by viktorbenei** [comment]
Use Secret Env Vars if you don't want to include something in your config, and don't grant admin access to those you don't want to have access to these information

**Comment by kartikbb** [comment]
Even Secret Env Vars will also be visible to admins. I may have developers that manage builds and hence are added as admins. But i still do not want them to be able to see the password.

**Comment by viktorbenei** [comment]
Makes sense, I guess adding a super admin role and restricting access of Secrets to this role would work. What do you think?  Would that be sufficient?

**Comment by kartikbb** [comment]
Well the least we can do is just mask the password for itunesconnect. Like we mask the password in the Code Signing Identity under workflow editor.

**Comment by viktorbenei** [comment]
This issue was moved to https://discuss.bitrise.io/t/provide-write-only-secret-env-vars-on-bitrise-io-dont-show-the-value-on-the-web-ui-after-its-set/146
