### ISSUE TITLE
CPU pegged in Chrome

### ISSUE THREAD

**Issue by kentcb** [bitrise-io/bitrise.io#83]
When kicking off a build, I have to remember to navigate _away_ from the build page because otherwise my CPU will become pegged at 100% and I will be forced to close the tab and re-open.

This was true when I was using Chrome on a Mac, but also true on Windows. My current Chrome version is 53.0.2785.143 m (64-bit).

**Comment by erosdome** [comment]
Hi, thanks for reporting the issue. We've recevied the same complaint about the build page recently, so we're looking into it. I will inform you once it is fixed.

**Comment by viktorbenei** [comment]
This issue was moved to https://discuss.bitrise.io/t/cpu-pegged-in-chrome/162
