### ISSUE TITLE
Add "Hobby Plus" pricing tier

### ISSUE THREAD

**Issue by derrickshowers** [bitrise-io/bitrise.io#86]
There should be a pricing tier between Hobby and Pro.

Hobby is great, but the 10 minute build time limit is quite limiting. For example, I tried it with what I'd consider to be pretty minimum on a relatively small app – build the app, test it, create an archive, upload it. Right now the build time is 9-11 minutes on average. I would love to add some more steps, and would be willing to pay a monthly fee, but $50 is pretty pricey for something that at the end of the day is still a hobby project.

I'd suggest a "Hobby Plus" option (or whatever you want to call it, I'm not always the best when it comes to naming things) to provide bitrise.io with some revenue, but not scare people away.

Thanks!

**Comment by viktorbenei** [comment]
Thanks for your feedback @derrickshowers!

We're definitely thinking about a pricing plan between free and the PRO ($50) plan, and right now you can get the 1xPRO plan for $25 if you contribute (and maintain) a step to the Bitrise StepLib: https://github.com/bitrise-io/bitrise-contrib

That said, feel free to vote and comment on this feature request, anyone who would like to see a mid tier plan - don't forget to describe what the limits would be (the way @derrickshowers did)!

**Comment by viktorbenei** [comment]
This issue was moved to https://discuss.bitrise.io/t/add-hobby-plus-pricing-tier/144

**Comment by shafatali** [comment]
For more detail please visit: [my hobby](http://persianpast.com/essay-on-my-hobby/)
