### ISSUE TITLE
Builds are timing out with new stack

### ISSUE THREAD

**Issue by sicruse** [bitrise-io/bitrise.io#89]
Hi - recently changed to using XCode 8.1 & the associated stack on bitrise is timing out our build. It used to complete in ~7-10 mins; now times out after 20+

**Comment by viktorbenei** [comment]
What's the last ~10 line of the log before the timeout?

**Comment by sicruse** [comment]
[20:42:42]: ▸ Copying Wink2/Comfortaa\ 300.ttf
[20:42:42]: ▸ Compiling CameraOverlay.xib
[20:42:44]: ▸ Copying Wink2/Comfortaa\ regular.ttf
[20:42:44]: ▸ Copying Wink2/Comfortaa\ 700.ttf
[20:42:44]: ▸ Compiling LaunchScreen.xib
[20:42:44]: ▸ Compiling Main.storyboard
[20:42:50]: ▸ Processing Info.plist
[20:42:50]: ▸ Generating 'Wink2.app.dSYM'
[20:42:50]: ▸ Running script 'Run Script'
[20:42:50]: ▸ Running script '[CP] Embed Pods Frameworks'

**Comment by viktorbenei** [comment]
Can you please send us the whole log in email?

**Comment by sicruse** [comment]
Sent to letsconnect@bitrise.io

**Comment by viktorbenei** [comment]
Thank you!

**Comment by viktorbenei** [comment]
This turned out to be an issue with `fastlane` + macOS Sierra combination. Reported at: https://github.com/fastlane/fastlane/issues/6866

**Comment by guidomb** [comment]
Not really sure if this is a bug in Fastlane or Bitrise but I was experimenting the same issue. copy-frameworks Carthage scripts was freezing. In my case I was creating a new keychain and that was making xcode freeze for some reason.

**Comment by viktorbenei** [comment]
> In my case I was creating a new keychain and that was making xcode freeze for some reason.

This is most likely an issue in your script / in fastlane, our own steps work properly, no freezing. Creating a new keychain can definitely be an issue, as the proper syntax / commands were changed in Sierra, to suppress the access grant popups.
