### ISSUE TITLE
Git clone step trying to clone submodules when there's no submodule

### ISSUE THREAD

**Issue by laeroah** [bitrise-io/bitrise.io#91]
My project structure is a little bit special: I have one private git repo storing a project and inside this project, I have a folder called 'UIFramework' which has content that I store in a public git repo. This somehow makes Bitrise think I have submodules and fails with "fatal: No url found for submodule path 'UIFramework' in .gitmodules"

I double checked, and there's no submodule used in my project. Please help. Thank you.

```
Retrying...
  => git "submodule" "update" "--init" "--recursive"
1 attempt failed:
fatal: No url found for submodule path 'UIFramework' in .gitmodules


Retrying...
  => git "submodule" "update" "--init" "--recursive"
2 attempt failed:
fatal: No url found for submodule path 'UIFramework' in .gitmodules

Failed, error: fatal: No url found for submodule path 'UIFramework' in .gitmodules

exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | git-clone@3.4.0 (exit code: 1)                                | 16 sec   |
```

**Comment by viktorbenei** [comment]
Most likely http://stackoverflow.com/questions/20168942/no-submodule-mapping-found-in-gitmodules-for-path-sinatra-bootstrap

P.S. please don't submit bug reports here, either send it to the step's github issue tracker or to the `build.issues` repo (https://github.com/bitrise-io/bitrise.io#report-an-issue--bug)
