### ISSUE TITLE
Build elapsed times & % complete incorrect

### ISSUE THREAD

**Issue by amayers** [bitrise-io/bitrise.io#92]
Seeing many of our builds having negative elapsed times where the numbers fluctuate wildly. Also the % complete is often also outside `0-100`

![screen shot 2016-11-10 at 3 33 23 pm](https://cloud.githubusercontent.com/assets/868103/20193231/239582f2-a75b-11e6-8003-a5a087d0cd11.png)

**Comment by viktorbenei** [comment]
Should be fixed by now, sorry for the issue.

P.S.: the times should be normalized once the build is finished, so this issue should only affect your build while it is running, and this is only a UI issue, it does not affect the build.
