### ISSUE TITLE
Build status images are missing Access-Control-Allow-Origin headers

### ISSUE THREAD

**Issue by cayblood** [bitrise-io/bitrise.io#93]
Because the endpoint that serves my bitrise build status images is missing an `Access-Control-Allow-Origin "*"` header, I'm unable to request it via ajax. Please fix this so that the image can be requested from anywhere.

**Comment by viktorbenei** [comment]
Thanks for the request @cayblood !

@erosdome @doomsayer13 please schedule this

**Comment by doomsayer13** [comment]
The fix is released.
@cayblood Let us know if that wouldn't solve the issue or if there are any other problems.
