### ISSUE TITLE
Add Steps to Deploy UITests to Xamarin Test Cloud When The App is Written in Xcode and the UI Tests are Written in C# (Xamarin.UITest)

### ISSUE THREAD

**Issue by brminnick** [bitrise-io/bitrise.io#95]
# Feature Request: Add officially supported steps that enable users to build their UI Test and deploy their UI tests to Xamarin Test Cloud when their app is written in Xcode and the UI Tests are written in C#/Xamarin.UITest

Below is the Workflow that I put together with great help from @godrei and @bradumbaugh!

## Stack
Use the Xamarin Stable Stack
<img width="1057" alt="screen shot 2016-11-14 at 9 11 13 am" src="https://cloud.githubusercontent.com/assets/13558917/20274683/62782ae6-aa4a-11e6-906a-4addc8d99732.png">

## Workflow 
<img width="966" alt="screen shot 2016-11-14 at 9 12 27 am" src="https://cloud.githubusercontent.com/assets/13558917/20274730/829cd29a-aa4a-11e6-9108-f3e52bdc201d.png">

### Build UITest
```
#!/bin/bash
# fail if any commands fails
set -e
# debug log
set -x

# write your script here
SOLUTION_FILE=`find . -name YOUR_UITEST_SOLUTION_FILENAME.sln`

"/Applications/Xamarin Studio.app/Contents/MacOS/mdtool" "build" $SOLUTION_FILE "-c:Debug" "-p:YOUR_UITEST_PROJECT_NAME"

envman add --key ASSEMBLY_DIR --value "/Users/vagrant/git/FOLDER_PATH_TO_YOUR_UITEST_PROJECT/bin/Debug"
```

### Submit to XTC
```
#!/bin/bash
# fail if any commands fails
set -e
# debug log
set -x

# write your script here
MONO="/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono" 
TEST_CLOUD=`find . -name test-cloud.exe`
UITestDll=`find . -name Xamarin.UITest.dll`

cp -f $UITestDll $ASSEMBLY_DIR

$MONO $TEST_CLOUD submit $BITRISE_IPA_PATH $TestCloudAPIKey --series "master" --locale "en_US" --user $TestCloudUserName --assembly-dir $ASSEMBLY_DIR --devices $TestCloudDeviceKey --async-json
```

Edit: Added step inside of "Submit to XTC' to copy `Xamarin.UITest.dll` into the Assembly Directory

**Comment by viktorbenei** [comment]
Thanks for the scripts @brminnick ! Labels added ;)

**Comment by brminnick** [comment]
Thanks @viktorbenei! @godrei was a huge help, and I couldn't have done it without him!

**Comment by brminnick** [comment]
Update: I added the following code to the "Submit to XTC" step, above to ensure that the `Xamarin.UITest.dll` is in the Assembly Directory.

```
UITestDll=`find . -name Xamarin.UITest.dll`

cp -f $UITestDll $ASSEMBLY_DIR
```

**Comment by viktorbenei** [comment]
Nice catch, thanks @brminnick ! ;)

**Comment by viktorbenei** [comment]
This issue was moved to https://discuss.bitrise.io/t/add-steps-to-deploy-uitests-to-xamarin-test-cloud-when-the-app-is-written-in-xcode-and-the-ui-tests-are-written-in-c-xamarin-uitest/151
