### ISSUE TITLE
Would be nice if there is an easy way to cancel all pending builds

### ISSUE THREAD

**Issue by yas375** [bitrise-io/bitrise.io#96]
Would be nice if there is an easy way to cancel all pending builds. For example we are investigating some flickering UI tests and wanted to run a workflow for a 100 times. Was easy to schedule with `curl`, but then it turned out there was a mistake and I had to open 100 pages, hit Abort button for another 100 times and then a 100 times I had to confirm the action. It's a little painful. :)

Thanks in advance!

(I've sent it to support first, and got a reply suggesting to post it here instead)

**Comment by viktorbenei** [comment]
Definitely a great idea, thanks for the feature request! (and don't forget to vote on it here ;) )

**Comment by viktorbenei** [comment]
This issue was moved to https://discuss.bitrise.io/t/would-be-nice-if-there-is-an-easy-way-to-cancel-all-pending-builds/149
